name: EventHelper
version: @version@
main: @main_class@
api-version: 1.13
authors: [DiaLight]
description: Useful tool to help event masters with theirs job

commands:
  eventhelper:
    description: Command to open eh gui
    aliases: [eh]
    permission: eventhelper.tool
    usage: /<command>

  tool:
    description: Command to control all registered tools
    permission: toollib.tool
    usage: /<command>
